# Generated by Django 5.0.4 on 2024-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailaccept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccept',
            name='user',
        ),
        migrations.AddField(
            model_name='emailaccept',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailaccept',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
