# Generated by Django 5.0.4 on 2024-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_emailaccept_user_emailaccept_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccept',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
