# Generated by Django 5.0.4 on 2024-04-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_remove_response_response_response_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
